apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: memshadow

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml
  - chromadb-deployment.yaml
  - memshadow-deployment.yaml
  - network-policy.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: memshadow
      app.kubernetes.io/version: "2.1"
      classification: unclassified
